USE petrescue_db;
SELECT AVG(COST) FROM PETRESCUE;
SELECT ROUND(AVG(COST),2) FROM PETRESCUE;
SELECT SUM(COST) FROM PETRESCUE;
SELECT SUM(COST) SUM_OF_COST FROM PETRESCUE;
SELECT ROUND(SUM(COST),2) FROM PETRESCUE;
SELECT MAX(COST) FROM PETRESCUE;
SELECT MIN(COST) FROM PETRESCUE;
SELECT COUNT(*) FROM PETRESCUE;
SELECT SUM(QUANTITY) AS Total_Animals
FROM PETRESCUE;
SELECT LENGTH(ANIMAL) FROM PETRESCUE;
SELECT UCASE(ANIMAL) FROM PETRESCUE;
SELECT LCASE(ANIMAL) FROM PETRESCUE;
SELECT DAY(RESCUEDATE) FROM PETRESCUE;
SELECT MONTH(RESCUEDATE) FROM PETRESCUE;
SELECT YEAR(RESCUEDATE) FROM PETRESCUE;
SELECT DATE_ADD(RESCUEDATE, INTERVAL 3 DAY)
FROM PETRESCUE;
SELECT DATE_ADD(RESCUEDATE, INTERVAL 2 MONTH)
FROM PETRESCUE;
SELECT DATE_SUB(RESCUEDATE, INTERVAL 3 DAY)
FROM PETRESCUE;
SELECT DATEDIFF(CURRENT_DATE, RESCUEDATE)
FROM PETRESCUE;
SELECT FROM_DAYS(DATEDIFF(CURRENT_DATE, RESCUEDATE)
) FROM PETRESCUE;
SELECT AVG(COST/QUANTITY) FROM PETRESCUE 
WHERE ANIMAL = 'Dog'; 
SELECT DISTINCT UCASE(ANIMAL) FROM PETRESCUE;
SELECT LCASE(ANIMAL) FROM PETRESCUE 
WHERE ANIMAL = 'Cat';
SELECT SUM(QUANTITY) FROM PETRESCUE 
WHERE MONTH(RESCUEDATE) = '05';
SELECT ID, DATE_ADD(RESCUEDATE, INTERVAL 1 YEAR ) 
FROM PETRESCUE;
